"""Fix LGA foreign key

Revision ID: 0cbdf89ad94f
Revises: 
Create Date: 2026-07-04 14:10:24.144821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cbdf89ad94f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lgas',
    sa.Column('lga_id', sa.Integer(), nullable=False),
    sa.Column('lga_name', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.state_id'], ),
    sa.PrimaryKeyConstraint('lga_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('user')
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('state_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.alter_column('state_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.drop_table('lgas')
    # ### end Alembic commands ###
