"""add is_admin column

Revision ID: 5c826809a87f
Revises: 0cbdf89ad94f
Create Date: 2026-07-06 00:30:23.620343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c826809a87f'
down_revision = '0cbdf89ad94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_entries')
    op.drop_table('markets')
    op.drop_table('admin')
    op.drop_table('products')
    with op.batch_alter_table('lgas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lga_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('lgas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('lga_id')

    op.create_table('products',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('product_image', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('unit_of_measure', mysql.VARCHAR(length=20), server_default=sa.text("'Kg'"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin',
    sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('markets',
    sa.Column('market_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('market_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('lga_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('state_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('market_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('price_entries',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('state_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('lga_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('source_type', mysql.ENUM('Farm', 'Market'), server_default=sa.text("'Market'"), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('notes', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('submitted_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_submitted', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('is_approved', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lga_id'], ['lgas.id'], name=op.f('price_entries_ibfk_3')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('price_entries_ibfk_1')),
    sa.ForeignKeyConstraint(['state_id'], ['states.state_id'], name=op.f('price_entries_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
